/* BUSPHOTO non-blocking modular loader v78 */
(function(){
'use strict';
if(window.__BUSPHOTO_INTERACTIVE_LOADER_V78__)return;
window.__BUSPHOTO_INTERACTIVE_LOADER_V78__=true;
const VERSION='20260828-v106';
const sections=[['menu','interactive-menu.html','interactive-menu-host'],['map','interactive-map.html','interactive-section-host-map'],['shop','interactive-shop.html','interactive-section-host-shop'],['garage','interactive-garage.html','interactive-section-host-garage'],['finance','interactive-finance.html','interactive-section-host-finance'],['history','interactive-history.html','interactive-section-host-history'],['routes','interactive-routes.html','interactive-section-host-routes'],['dispatch','interactive-dispatch.html','interactive-section-host-dispatch'],['stats','interactive-stats.html','interactive-section-host-stats'],['maintenance','interactive-maintenance.html','interactive-section-host-maintenance'],['sync','interactive-sync.html','interactive-section-host-sync'],['rules','interactive-rules.html','interactive-rules-host']];
const byName=Object.fromEntries(sections.map(x=>[x[0],x])),loaded=new Set(),loading=new Map();
function status(t,e){const x=document.getElementById('interactiveLoadingStatus');if(x){x.textContent=t;x.style.display='';x.style.borderColor=e?'#d32f2f':'';}}
async function fetchWithTimeout(url,ms){const c=new AbortController(),t=setTimeout(()=>c.abort(),ms);try{return await fetch(url,{cache:'default',credentials:'same-origin',signal:c.signal});}finally{clearTimeout(t);}}
async function loadOne(name,opts={}){const item=byName[name];if(!item)return false;if(loaded.has(name))return true;if(loading.has(name))return loading.get(name);const [,file,hostId]=item;const p=(async()=>{const host=document.getElementById(hostId);if(!host)throw new Error('Host not found: '+hostId);if(host.querySelector('#game-section-'+name)){loaded.add(name);if(name==='sync')initSync();return true;}host.replaceChildren();const r=await fetchWithTimeout(file+'?v='+VERSION,opts.timeout||8000);if(!r.ok)throw new Error(file+' HTTP '+r.status);host.innerHTML=await r.text();loaded.add(name);if(name==='garage'&&typeof renderGarageSection==='function')renderGarageSection();if(name==='history'&&typeof renderHistorySection==='function')renderHistorySection();if(name==='sync')initSync();return true;})();loading.set(name,p);try{return await p;}finally{loading.delete(name);}}
function initSync(){if(window.__BUSPHOTO_SYNC_INIT_PENDING__)return;window.__BUSPHOTO_SYNC_INIT_PENDING__=true;const run=()=>{if(typeof window.BUSPHOTOInitSync==='function')window.BUSPHOTOInitSync().catch(e=>console.warn('[BUSPHOTO sync]',e));};if(document.getElementById('busphotoSyncScript')){run();return;}const s=document.createElement('script');s.id='busphotoSyncScript';s.src='interactive-sync.js?v='+VERSION;s.onload=run;s.onerror=()=>status('Не удалось загрузить модуль синхронизации.',true);document.head.appendChild(s);}
function refreshSectionData(section){try{if(section==='finance'){const a=document.getElementById('financeBalance'),b=document.getElementById('financeOwned'),c=document.getElementById('financeLastPayout');if(typeof gameState!=='undefined'){if(a)a.textContent=typeof money==='function'?money(gameState.balance):`${Math.round(Number(gameState.balance||0)).toLocaleString('ru-RU')} р.`;if(b)b.textContent=Array.isArray(gameState.owned)?gameState.owned.length:0;if(c)c.textContent=gameState.lastPayoutDate||'ещё не было';}}else if(section==='garage'&&typeof renderGarageSection==='function')renderGarageSection();else if(section==='history'&&typeof renderHistorySection==='function')renderHistorySection();else if(section==='routes'&&typeof renderRoutes==='function')renderRoutes();else if((section==='dispatch'||section==='stats'||section==='maintenance')&&typeof renderV43Panels==='function')renderV43Panels();}catch(e){console.warn('[BUSPHOTO] refresh',e);}}
window.openInteractiveSection=async function(section,btn){try{await loadOne(section,{timeout:8000});if(typeof window.showGameSection==='function'){window.showGameSection(section,btn);refreshSectionData(section);}}catch(e){console.error('[BUSPHOTO] section',section,e);status('Раздел не удалось загрузить. Попробуй открыть его ещё раз.',true);}};
window.BUSPHOTOEnsureInteractiveSection=loadOne;
async function loadMain(){if(document.querySelector('script[data-busphoto-interactive-main]'))return;await new Promise((resolve,reject)=>{const s=document.createElement('script');s.dataset.busphotoInteractiveMain='1';s.src='busphoto-interactive.js?v='+VERSION;s.onload=resolve;s.onerror=()=>reject(new Error('busphoto-interactive.js'));document.head.appendChild(s);});}
async function start(){status('Запуск интерактива…');try{await loadOne('menu');await loadMain();}catch(e){console.error(e);status('Не удалось запустить интерактивный модуль.',true);return;}const init=()=>{if(typeof window.__BUSPHOTO_INIT_INTERACTIVE_GAME__!=='function'||window.__BUSPHOTO_GAME_INITIALIZED__)return;try{window.__BUSPHOTO_INIT_INTERACTIVE_GAME__();window.__BUSPHOTO_GAME_INITIALIZED__=true;}catch(e){console.error(e);}};if(typeof window.ensureLeafletLoaded==='function')Promise.resolve().then(()=>window.ensureLeafletLoaded()).catch(()=>{});init();loadOne('shop').then(()=>{if(!window.__BUSPHOTO_GAME_INITIALIZED__)init();}).catch(()=>{});const st=document.getElementById('interactiveLoadingStatus');if(st)st.style.display='none';const rest=['garage','finance','history','routes','rules'];let i=0;const next=()=>{if(i>=rest.length)return;loadOne(rest[i++]).catch(()=>{});if('requestIdleCallback'in window)requestIdleCallback(next,{timeout:1500});else setTimeout(next,80);};next();}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
})();
