/* BUSPHOTO main database cloud sync — Google OAuth + Supabase. */
(function(){
'use strict'; if(window.__BUSPHOTO_MAIN_SYNC__)return; window.__BUSPHOTO_MAIN_SYNC__=true;
const SUPABASE_URL='https://ubhfigqpsepnpokrbdyo.supabase.co', SUPABASE_KEY='sb_publishable_yN8W8pvQq8hWsYMO8z1Rzw_6zKQ-8D1', TABLE='busphoto_main_state', ROW_ID='database', DB_KEY='busphoto_custom_db';
let sb=null,user=null,timer=null,channel=null,applying=false; const $=id=>document.getElementById(id);
function status(t,e=false){const x=$('mainSyncStatus');if(x){x.textContent=t;x.style.borderColor=e?'#c62828':'';}}
function read(){try{return JSON.parse(localStorage.getItem(DB_KEY)||'[]')}catch{return[]}}
function info(extra=''){const x=$('mainSyncInfo');if(x)x.textContent=`Локальная БД: ${read().length} ТС${extra?' · '+extra:''}`}
function redirect(){return location.origin+location.pathname+location.hash}
async function sdk(){if(window.supabase?.createClient)return window.supabase;if(window.__BUSPHOTO_MAIN_SDK__)return window.__BUSPHOTO_MAIN_SDK__;return window.__BUSPHOTO_MAIN_SDK__=new Promise((ok,bad)=>{const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2';s.async=true;s.onload=()=>window.supabase?.createClient?ok(window.supabase):bad(new Error('Supabase SDK не инициализировался'));s.onerror=()=>bad(new Error('Не удалось загрузить Supabase SDK'));document.head.appendChild(s)})}
function render(){const on=!!user;if($('mainSyncAuth'))$('mainSyncAuth').style.display=on?'none':'';if($('mainSyncPanel'))$('mainSyncPanel').style.display=on?'':'none';if($('mainSyncUser'))$('mainSyncUser').textContent=on?`👤 ${user.email||user.user_metadata?.email||'Google аккаунт'}`:'';if($('mainSyncAuto'))$('mainSyncAuto').checked=localStorage.getItem('busphoto_main_sync_auto_v1')==='1';info()}
async function loginGoogle(){status('🔐 открываю Google...');const r=await sb.auth.signInWithOAuth({provider:'google',options:{redirectTo:redirect(),queryParams:{prompt:'select_account'}}});if(r.error)throw r.error}
async function loginEmail(){const e=$('mainSyncEmail').value.trim(),p=$('mainSyncPassword').value;if(!e||!p)return status('Введите email и пароль.',true);const r=await sb.auth.signInWithPassword({email:e,password:p});if(r.error)throw r.error}
async function signup(){const e=$('mainSyncEmail').value.trim(),p=$('mainSyncPassword').value;if(!e||!p)return status('Введите email и пароль.',true);if(p.length<6)return status('Пароль минимум 6 символов.',true);const r=await sb.auth.signUp({email:e,password:p,options:{emailRedirectTo:redirect()}});if(r.error)throw r.error;status(r.data.session?'✅ аккаунт создан.':'📨 Проверь почту и подтверди email.')}
async function row(){const r=await sb.from(TABLE).select('id,data,updated_at').eq('user_id',user.id).eq('id',ROW_ID).maybeSingle();if(r.error)throw r.error;return r.data}
async function save(silent=false){if(!user||applying)return;try{if(!silent)status('☁️ сохраняю основную БД...');const data=read(),now=new Date().toISOString();const r=await sb.from(TABLE).upsert({user_id:user.id,id:ROW_ID,data:{version:1,savedAt:now,vehicleDB:data},updated_at:now},{onConflict:'user_id,id'});if(r.error)throw r.error;if(!silent)status('✅ основная БД сохранена в облако');info('синхронизировано')}catch(e){status('⚠️ ошибка сохранения: '+(e.message||e),true)}}
async function inspect(){if(!user)return;try{const r=await row();status(r?`☁️ в облаке: ${(r.data?.vehicleDB||[]).length} ТС · ${new Date(r.updated_at).toLocaleString('ru-RU')}`:'☁️ облачной БД пока нет. Сохрани текущую БД.')}catch(e){status('⚠️ не удалось проверить облако: '+(e.message||e),true)}}
async function load(){if(!user)return;try{const r=await row();if(!r)return status('☁️ В облаке пока нет БД. Сначала сохрани её.',true);const db=Array.isArray(r.data?.vehicleDB)?r.data.vehicleDB:null;if(!db)throw new Error('облачная запись повреждена');if(!confirm(`Загрузить БД из облака?\n\nОблако: ${db.length} ТС\nЛокально: ${read().length} ТС\n\nЛокальная БД будет заменена.`))return status('Загрузка отменена.');applying=true;localStorage.setItem(DB_KEY,JSON.stringify(db));applying=false;window.vehicleDB=JSON.parse(JSON.stringify(db));if(typeof renderTable==='function')renderTable();status('✅ БД загружена из облака.');info('загружено из облака')}catch(e){applying=false;status('⚠️ ошибка загрузки: '+(e.message||e),true)}}
function schedule(){if(user&&!applying&&localStorage.getItem('busphoto_main_sync_auto_v1')==='1'){clearTimeout(timer);timer=setTimeout(()=>save(true),900)}}
function hook(){if(window.__BUSPHOTO_MAIN_HOOK__)return;window.__BUSPHOTO_MAIN_HOOK__=true;const old=Storage.prototype.setItem;Storage.prototype.setItem=function(k,v){const r=old.apply(this,arguments);if(k===DB_KEY&&!applying)window.dispatchEvent(new Event('busphoto-db-changed'));return r};window.addEventListener('busphoto-db-changed',()=>{info();schedule()})}
function realtime(){if(channel)sb.removeChannel(channel);channel=sb.channel('busphoto-main-'+user.id).on('postgres_changes',{event:'*',schema:'public',table:TABLE,filter:`user_id=eq.${user.id}`},inspect).subscribe()}
async function logout(){if(channel)sb.removeChannel(channel);channel=null;await sb.auth.signOut();user=null;render();status('Вы вышли из облачного аккаунта.')}
async function init(){if(!$('mainSyncRoot'))return;hook();$('mainSyncGoogle').onclick=()=>loginGoogle().catch(e=>status('⚠️ Google-вход: '+(e.message||e),true));$('mainSyncLogin').onclick=()=>loginEmail().catch(e=>status('⚠️ вход: '+(e.message||e),true));$('mainSyncSignup').onclick=()=>signup().catch(e=>status('⚠️ регистрация: '+(e.message||e),true));$('mainSyncSave').onclick=()=>save();$('mainSyncLoad').onclick=()=>load();$('mainSyncLogout').onclick=()=>logout();$('mainSyncAuto').onchange=()=>{localStorage.setItem('busphoto_main_sync_auto_v1',$('mainSyncAuto').checked?'1':'0');status($('mainSyncAuto').checked?'🔄 автосинхронизация включена.':'Автосинхронизация выключена.');if($('mainSyncAuto').checked)save(true)};render();try{const S=await sdk();sb=S.createClient(SUPABASE_URL,SUPABASE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});const r=await sb.auth.getSession();user=r.data.session?.user||null;render();if(user){realtime();inspect()}else status('🔐 Войди через Google, чтобы синхронизировать основную БД.');sb.auth.onAuthStateChange((_e,s)=>{user=s?.user||null;render();if(user){realtime();setTimeout(inspect,0)}else if(channel){sb.removeChannel(channel);channel=null}})}catch(e){status('⚠️ '+(e.message||e),true)}}
window.BUSPHOTOInitMainSync=init;
})();
